# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('user', models.IntegerField()),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=40, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('policy_type', models.CharField(choices=[('Traditional', 'Traditional'), ('ULIP', 'ULIP'), ('Term', 'Term'), ('Health', 'Health')], max_length=50)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('buy_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('latest_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('gain', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('sum_assured', models.DecimalField(decimal_places=0, default=0, max_digits=20, null=True)),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
                ('mortality_charges', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
            options={
                'unique_together': {('policy', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=40, null=True)),
                ('fund_type', models.CharField(blank=True, max_length=40, null=True)),
                ('units', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('nav', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('nav_date', models.DateField(blank=True, null=True)),
                ('return_1d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1D')),
                ('return_1w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1W')),
                ('return_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1M')),
                ('return_3m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3M')),
                ('return_6m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='6M')),
                ('return_1y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1Y')),
                ('return_3y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3Y')),
                ('return_5y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='5Y')),
                ('return_10y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='10Y')),
                ('return_15y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='15Y')),
                ('return_incep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Inception')),
                ('return_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='YTD')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancepolicy')),
            ],
            options={
                'unique_together': {('policy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=40)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('trans_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('description', models.CharField(max_length=40)),
                ('trans_type', models.CharField(choices=[('Premium', 'Premium'), ('OtherCharges', 'OtherCharges'), ('OtherCredits', 'OtherCredits'), ('PolicyAdminCharges', 'PolicyAdminCharges'), ('CentralGST', 'CentralGST'), ('StateGST', 'StateGST'), ('OtherDeductions', 'OtherDeductions'), ('MortalityCharges', 'MortalityCharges'), ('OtherTaxes', 'OtherTaxes')], max_length=50)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.fund')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.insurancepolicy')),
            ],
            options={
                'unique_together': {('policy', 'trans_date', 'trans_amount', 'description')},
            },
        ),
        migrations.CreateModel(
            name='NAVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('nav_date', models.DateField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.fund')),
            ],
            options={
                'unique_together': {('fund', 'nav_date')},
            },
        ),
    ]
