# Generated by Django 5.0.11 on 2025-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_period', models.IntegerField()),
                ('final_val', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('mat_date', models.DateField()),
            ],
            options={
                'unique_together': {('number', 'bank_name')},
            },
        ),
    ]
