# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEMonthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=60)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pe_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_min', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('index_name', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PBMonthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=60)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pb_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pb_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pb_min', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('index_name', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=6000)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=6000)),
                ('source', models.CharField(max_length=60)),
            ],
            options={
                'unique_together': {('exchange', 'symbol', 'text', 'date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='IndexYearlyReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('ret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
            ],
            options={
                'unique_together': {('country', 'name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IndexRollingReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('return_1d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1D')),
                ('return_1w', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1W')),
                ('return_1m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1M')),
                ('return_3m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3M')),
                ('return_6m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='6M')),
                ('return_1y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1Y')),
                ('return_3y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3Y')),
                ('return_5y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='5Y')),
                ('return_10y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='10Y')),
                ('return_15y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='15Y')),
                ('return_incep', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Inception')),
                ('return_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='YTD')),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IndexQuarterlyReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=10)),
                ('ret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
            ],
            options={
                'unique_together': {('country', 'name', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='IndexMonthlyReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=10)),
                ('ret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
            ],
            options={
                'unique_together': {('country', 'name', 'month')},
            },
        ),
    ]
