# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Scheduled'), (2, 'Running'), (3, 'Failed'), (4, 'Successful')], default=0)),
                ('notes', models.TextField(blank=True, max_length=600, null=True)),
                ('task_name', models.CharField(max_length=60)),
                ('current_state', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Scheduled'), (2, 'Running'), (3, 'Failed'), (4, 'Successful')], default=0)),
            ],
        ),
    ]
