# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('total_networth', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('as_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
