# Generated by Django 5.0.11 on 2025-09-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='risk_profile',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetClassDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateTimeField(blank=True, default='', null=True)),
                ('suggested_equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suggested_debt_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_debt_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_debt_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suggested_gold_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_gold_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_gold_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suggested_crypto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_crypto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_crypto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suggested_cash_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_cash_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_cash_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
