# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentData',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('as_on_date', models.DateTimeField(blank=True, null=True)),
                ('start_day_across_portfolio', models.DateField(blank=True, null=True)),
                ('ppf_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('epf_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('ssy_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('fd_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('espp_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('rsu_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('shares_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('mf_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('r401k_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('insurance_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('gold_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('cash_data', models.CharField(blank=True, max_length=6000, null=True)),
                ('loan_data', models.CharField(blank=True, default='', max_length=6000, null=True)),
                ('crypto_data', models.CharField(blank=True, default='', max_length=6000, null=True)),
                ('total_data', models.CharField(blank=True, max_length=6000, null=True)),
            ],
        ),
    ]
