# Generated by Django 5.0.11 on 2025-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdata',
            name='rd_data',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
