# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('curr_val', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time_period', models.IntegerField()),
                ('inflation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_val', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.IntegerField()),
                ('recurring_pay_goal', models.BooleanField()),
                ('expense_period', models.IntegerField(blank=True, null=True)),
                ('post_returns', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('equity_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('debt_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('achieved_amt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_amt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('achieved_percent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pending_percent', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('epf_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('espp_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fd_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ppf_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ssy_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rsu_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('shares_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mf_conitrib', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('r_401k_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('insurance_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gold_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('crypto_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
