# Generated by Django 5.0.11 on 2025-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='rd_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
