# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.IntegerField()),
                ('goal', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=40, null=True)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('interest_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('withdrawl', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('uan', models.CharField(blank=True, max_length=50, null=True)),
                ('eps', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('number', 'company')},
            },
        ),
        migrations.CreateModel(
            name='EpfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('notes', models.CharField(max_length=40)),
                ('reference', models.CharField(max_length=20)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('interest_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('withdrawl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('epf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epf.epf')),
            ],
            options={
                'unique_together': {('epf_id', 'trans_date')},
            },
        ),
    ]
