# Generated by Django 4.1 on 2022-08-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ppf',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('user', models.IntegerField()),
                ('goal', models.IntegerField(null=True)),
                ('notes', models.CharField(blank=True, max_length=40, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('interest_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PpfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField()),
                ('notes', models.CharField(max_length=40)),
                ('reference', models.CharField(max_length=20)),
                ('entry_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], default='CR', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_component', models.BooleanField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppf.ppf')),
            ],
            options={
                'unique_together': {('number', 'trans_date', 'entry_type', 'interest_component')},
            },
        ),
    ]
