# Generated by Django 4.1 on 2022-08-28 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=3)),
                ('user', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('as_on_date', models.DateField(blank=True, null=True, verbose_name='As On Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('acc_type', models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking'), ('Current', 'Current'), ('HomeLoan', 'Home Loan'), ('CarLoan', 'Car Loan'), ('PersonalLoan', 'Personal Loan'), ('OtherLoan', 'Other Loan'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
            options={
                'unique_together': {('number', 'bank_name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(verbose_name='Transaction Date')),
                ('trans_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('category', models.CharField(blank=True, choices=[('Card Payment', 'Card Payment'), ('Interest', 'Interest'), ('Shopping', 'Shopping'), ('EMI/Loan Payment', 'EMI/Loan Payment'), ('Fuel', 'Fuel'), ('Other', 'Other'), ('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Investment', 'Investment'), ('Child Education', 'Child Education'), ('Vacation', 'Vacation'), ('Entertainment', 'Entertainment'), ('Utility', 'Utility'), ('Gift', 'Gift'), ('Salary/Payment', 'Salary/Payment'), ('Insurance', 'Insurance'), ('Self Transfer', 'Self Transfer')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('tran_id', models.CharField(blank=True, max_length=30, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount')),
            ],
            options={
                'unique_together': {('account', 'trans_date', 'amount', 'trans_type', 'description', 'notes', 'tran_id')},
            },
        ),
    ]
