# Generated by Django 5.0.11 on 2025-09-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Card Payment', 'Card Payment'), ('Interest', 'Interest'), ('Shopping', 'Shopping'), ('EMI/Loan Payment', 'EMI/Loan Payment'), ('Fuel', 'Fuel'), ('Other', 'Other'), ('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Medical', 'Medical'), ('Charity', 'Charity'), ('Investment', 'Investment'), ('Education', 'Education'), ('Expense Split', 'Expense Split'), ('Child Education', 'Child Education'), ('Vacation', 'Vacation'), ('Entertainment', 'Entertainment'), ('Utility', 'Utility'), ('Gift', 'Gift'), ('Salary/Payment', 'Salary/Payment'), ('Insurance', 'Insurance'), ('Self Transfer', 'Self Transfer'), ('Shares Dividends', 'Shares Dividends'), ('Other Dividends', 'Other Dividends')], max_length=20, null=True),
        ),
    ]
