# Generated by Django 4.1 on 2022-09-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='api_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='symbol_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
