# Generated by Django 4.1 on 2022-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='email_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='email_api_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='email_backend',
            field=models.CharField(blank=True, choices=[('Mailjet', 'Mailjet')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
