name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Copy .env file
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        pwd
        ls -la "$GITHUB_WORKSPACE" || true
        if [ ! -d "$GITHUB_WORKSPACE/env_files" ]; then
          echo "No env_files directory at $GITHUB_WORKSPACE/env_files. Skipping copy."
          exit 0
        fi
        echo "Copying env_files/default_docker/* -> env_files/"
        cp "$GITHUB_WORKSPACE/env_files/default_docker/"* "$GITHUB_WORKSPACE/env_files/"
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/portfoliomanager:latest
